### ISSUE TITLE
Why not just use a struct?

### ISSUE THREAD

**Issue by johnfredcee** [cbaggers/structy-defclass#2]
Seems like wheel reinvention

**Comment by cbaggers** [comment]
On sbcl redefining a struct with type specifiers is very painful (have to recompile everything that touched it) if the changes are too drastic sometimes the compiler just cant resolve the issue and you have to restart your 'session'. Classes can have their slots added and removed without this issue. Then after I have finished working out the details of the program I just swap deftclass for defstruct, everything keeps working and the I get all the advantages of struct

**Comment by cbaggers** [comment]
Good question though, I should add this to the readme.

**Comment by johnfredcee** [comment]
I did wonder! :-)
